scoreboard players operation @s[scores={qtitle_15=-1,qtitle_14=!-1}] qtitle_15 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_14=-1,qtitle_13=!-1}] qtitle_14 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_13=-1,qtitle_12=!-1}] qtitle_13 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_12=-1,qtitle_11=!-1}] qtitle_12 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_11=-1,qtitle_10=!-1}] qtitle_11 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_10=-1,qtitle_9=!-1}] qtitle_10 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_9=-1,qtitle_8=!-1}] qtitle_9 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_8=-1,qtitle_7=!-1}] qtitle_8 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_7=-1,qtitle_6=!-1}] qtitle_7 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_6=-1,qtitle_5=!-1}] qtitle_6 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_5=-1,qtitle_4=!-1}] qtitle_5 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_4=-1,qtitle_3=!-1}] qtitle_4 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_3=-1,qtitle_2=!-1}] qtitle_3 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_2=-1,qtitle_1=!-1}] qtitle_2 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_1=-1,qtitle_0=!-1}] qtitle_1 = @s qtitle_s
scoreboard players operation @s[scores={qtitle_0=-1}] qtitle_0 = @s qtitle_s