tag @s remove not_enough_chi.had
tag @s[tag=not_enough_chi] add not_enough_chi.had
tag @s remove not_enough_chi
tag @s[scores={technique_id=10,chi=..9}] add not_enough_chi
tag @s[scores={technique_id=11,chi=..29}] add not_enough_chi
tag @s[scores={technique_id=12,chi=..9}] add not_enough_chi
tag @s[scores={technique_id=20,chi=..19}] add not_enough_chi
tag @s[scores={technique_id=21,chi=..9}] add not_enough_chi
tag @s[scores={technique_id=22,chi=..4}] add not_enough_chi
tag @s[scores={technique_id=31,chi=..59}] add not_enough_chi
tag @s[scores={technique_id=32,chi=..9}] add not_enough_chi
tag @s[scores={technique_id=33,chi=..9}] add not_enough_chi
tag @s[scores={technique_id=42,chi=..19}] add not_enough_chi
tag @s[scores={technique_id=41,chi=..9}] add not_enough_chi
tag @s[scores={technique_id=40,chi=..9}] add not_enough_chi
event entity @s[tag=not_enough_chi,tag=!not_enough_chi.had] nom:add_not_enough_chi
event entity @s[tag=!not_enough_chi,tag=not_enough_chi.had] nom:remove_not_enough_chi