tag @s remove trinket.aang
tag @s remove trinket.amon
tag @s remove trinket.asami
tag @s remove trinket.azula
tag @s remove trinket.bolin
tag @s remove trinket.bumi
tag @s remove trinket.cabbage
tag @s remove trinket.iroh
tag @s remove trinket.jet
tag @s remove trinket.kai
tag @s remove trinket.katara
tag @s remove trinket.korra
tag @s remove trinket.kyoshi
tag @s remove trinket.lin
tag @s remove trinket.long
tag @s remove trinket.mako
tag @s remove trinket.opal
tag @s remove trinket.ozai
tag @s remove trinket.pathik
tag @s remove trinket.players
tag @s remove trinket.roku
tag @s remove trinket.sokka
tag @s remove trinket.suki
tag @s remove trinket.tenzin
tag @s remove trinket.toph
tag @s remove trinket.unalaq
tag @s remove trinket.varrick
tag @s remove trinket.zaheer
tag @s remove trinket.zhao
tag @s remove trinket.zuko