scoreboard players remove @s[scores={bc_earth_0=1..}] bc_earth_0 1
scoreboard players remove @s[scores={bc_earth_1=1..}] bc_earth_1 1
scoreboard players remove @s[scores={bc_earth_2=1..}] bc_earth_2 1
scoreboard players remove @s[scores={bc_earth_3=1..}] bc_earth_3 1
scoreboard players remove @s[scores={bc_earth_4=1..}] bc_earth_4 1
scoreboard players remove @s[scores={bc_water_0=1..}] bc_water_0 1
scoreboard players remove @s[scores={bc_water_1=1..}] bc_water_1 1
scoreboard players remove @s[scores={bc_water_2=1..}] bc_water_2 1
scoreboard players remove @s[scores={bc_water_3=1..}] bc_water_3 1
scoreboard players remove @s[scores={bc_water_4=1..}] bc_water_4 1
scoreboard players remove @s[scores={bc_air_0=1..}] bc_air_0 1
scoreboard players remove @s[scores={bc_air_1=1..}] bc_air_1 1
scoreboard players remove @s[scores={bc_air_2=1..}] bc_air_2 1
scoreboard players remove @s[scores={bc_air_3=1..}] bc_air_3 1
scoreboard players remove @s[scores={bc_air_4=1..}] bc_air_4 1
scoreboard players remove @s[scores={bc_fire_0=1..}] bc_fire_0 1
scoreboard players remove @s[scores={bc_fire_1=1..}] bc_fire_1 1
scoreboard players remove @s[scores={bc_fire_2=1..}] bc_fire_2 1
scoreboard players remove @s[scores={bc_fire_3=1..}] bc_fire_3 1
scoreboard players remove @s[scores={bc_fire_4=1..}] bc_fire_4 1