scoreboard players set @s bc_earth_0 0
scoreboard players set @s bc_earth_1 0
scoreboard players set @s bc_earth_2 0
scoreboard players set @s bc_earth_3 0
scoreboard players set @s bc_earth_4 0
scoreboard players set @s bc_water_0 0
scoreboard players set @s bc_water_1 0
scoreboard players set @s bc_water_2 0
scoreboard players set @s bc_water_3 0
scoreboard players set @s bc_water_4 0
scoreboard players set @s bc_air_0 0
scoreboard players set @s bc_air_1 0
scoreboard players set @s bc_air_2 0
scoreboard players set @s bc_air_3 0
scoreboard players set @s bc_air_4 0
scoreboard players set @s bc_fire_0 0
scoreboard players set @s bc_fire_1 0
scoreboard players set @s bc_fire_2 0
scoreboard players set @s bc_fire_3 0
scoreboard players set @s bc_fire_4 0