msg @a[tag=dev] Running scoreboard init
scoreboard objectives add init_v dummy
scoreboard objectives add init_v_cache dummy
scoreboard objectives add seconds_timer dummy
scoreboard objectives add 200ms_timer dummy
scoreboard objectives add stats dummy
scoreboard objectives add const dummy
scoreboard objectives add tmp dummy
scoreboard objectives add block_to_find dummy
scoreboard objectives add tp_blocks dummy
scoreboard players set n0 const 0
scoreboard players set n1 const 1
scoreboard players set n2 const 2
scoreboard players set n4 const 4
scoreboard players set n7 const 7
scoreboard players set n8 const 8
scoreboard players set n10 const 10
scoreboard players set n20 const 20
scoreboard players set n100 const 100
scoreboard objectives add technique_id dummy
scoreboard objectives add rc_hitblock_c dummy
scoreboard objectives add rc_aircount dummy
scoreboard objectives add rc_e_length dummy
scoreboard objectives add rc_w_length dummy
scoreboard objectives add bending_id dummy
scoreboard objectives add target_id dummy
scoreboard objectives add bending_id_cache dummy
scoreboard objectives add q_levitation dummy
scoreboard objectives add q_slowness dummy
scoreboard objectives add del_dmg_time dummy
scoreboard objectives add del_dmg_amnt dummy
scoreboard objectives add bc_earth_0 dummy
scoreboard objectives add bc_earth_1 dummy
scoreboard objectives add bc_earth_2 dummy
scoreboard objectives add bc_earth_3 dummy
scoreboard objectives add bc_earth_4 dummy
scoreboard objectives add bc_water_0 dummy
scoreboard objectives add bc_water_1 dummy
scoreboard objectives add bc_water_2 dummy
scoreboard objectives add bc_water_3 dummy
scoreboard objectives add bc_water_4 dummy
scoreboard objectives add bc_air_0 dummy
scoreboard objectives add bc_air_1 dummy
scoreboard objectives add bc_air_2 dummy
scoreboard objectives add bc_air_3 dummy
scoreboard objectives add bc_air_4 dummy
scoreboard objectives add bc_fire_0 dummy
scoreboard objectives add bc_fire_1 dummy
scoreboard objectives add bc_fire_2 dummy
scoreboard objectives add bc_fire_3 dummy
scoreboard objectives add bc_fire_4 dummy
scoreboard objectives add defence_rnd dummy
scoreboard objectives add defence_time dummy
scoreboard objectives add defence_cd dummy
scoreboard objectives add utils_distance dummy
scoreboard objectives add random_item dummy
scoreboard objectives add boost_rand dummy
scoreboard objectives add boost_dir dummy
scoreboard objectives add item_time dummy
scoreboard objectives add fire_sweep_itr dummy
scoreboard objectives add fire_jet_charge dummy
scoreboard objectives add earth_quake_time dummy
scoreboard objectives add movement_dir dummy
scoreboard objectives add glider_time dummy
scoreboard objectives add chi dummy
scoreboard objectives add chi_old dummy
scoreboard objectives add chi_to_use dummy
scoreboard objectives add chi_control dummy
scoreboard objectives add chi_fail dummy
scoreboard objectives add chi_water dummy
scoreboard objectives add chi_fail_cd dummy
scoreboard objectives add teq_state dummy
scoreboard objectives add dummy_health_0 dummy
scoreboard objectives add dummy_health_1 dummy
scoreboard objectives add dummy_id dummy
scoreboard objectives add flying_yaw dummy
scoreboard objectives add dummy_id dummy
scoreboard objectives add loop dummy
scoreboard objectives add tornado_cd dummy
scoreboard objectives add tornado_throw dummy
scoreboard objectives add tornado_dir dummy
scoreboard objectives add in_air dummy
scoreboard objectives add dummy_id dummy
scoreboard objectives add area_sel_max dummy
scoreboard objectives add projectile_time dummy
scoreboard objectives add tickas_id dummy
scoreboard objectives add tickas_id_cache dummy
scoreboard objectives add tickas_return_c dummy
scoreboard objectives add loop dummy
scoreboard objectives add spawner_id dummy
scoreboard objectives add spawner_tmp dummy
scoreboard objectives add spawner_count dummy
scoreboard objectives add spawner_buffer dummy
scoreboard objectives add encampment_prog dummy
scoreboard objectives add encampment_pc dummy
scoreboard objectives add encampment_val dummy
scoreboard objectives add encampment_bprog dummy
scoreboard objectives add encampbar dummy
scoreboard objectives add battle_state dummy
scoreboard objectives add battle_id dummy
scoreboard objectives add battle_outside dummy
scoreboard objectives add battle_exit dummy
scoreboard objectives add close_ui_in dummy
scoreboard objectives add ui_loaded dummy
scoreboard objectives add medidate_kick dummy
scoreboard objectives add scene_id dummy
scoreboard objectives add shot_id dummy
scoreboard objectives add shot_ts dummy
scoreboard objectives add facing_dir dummy
scoreboard objectives add roarer_id dummy
scoreboard objectives add roaree_id dummy
scoreboard objectives add roaree_id_c dummy
scoreboard objectives add roar_id dummy
scoreboard objectives add roar_dir dummy
scoreboard objectives add roar_dmg dummy
scoreboard objectives add roar_str dummy
scoreboard objectives add roar_cooldown dummy
scoreboard objectives add roar_cooldown_ts dummy
scoreboard players set previous roarer_id 0
scoreboard players set previous roar_id 0
scoreboard objectives add qtitle_s dummy
scoreboard objectives add qtitle_0 dummy
scoreboard objectives add qtitle_1 dummy
scoreboard objectives add qtitle_2 dummy
scoreboard objectives add qtitle_3 dummy
scoreboard objectives add qtitle_4 dummy
scoreboard objectives add qtitle_5 dummy
scoreboard objectives add qtitle_6 dummy
scoreboard objectives add qtitle_7 dummy
scoreboard objectives add qtitle_8 dummy
scoreboard objectives add qtitle_9 dummy
scoreboard objectives add qtitle_10 dummy
scoreboard objectives add qtitle_11 dummy
scoreboard objectives add qtitle_12 dummy
scoreboard objectives add qtitle_13 dummy
scoreboard objectives add qtitle_14 dummy
scoreboard objectives add qtitle_15 dummy
scoreboard objectives add qtitle_tick dummy
scoreboard objectives add qtitle_tsu dummy
scoreboard objectives add chi_tsu dummy
scoreboard objectives add ui_hud dummy
scoreboard objectives add ui_abpoints dummy
scoreboard objectives add warning dummy
scoreboard objectives add bossbar_id dummy
scoreboard objectives add bossbar_health dummy
scoreboard objectives add player_current dummy
scoreboard objectives add settlement_state dummy
scoreboard objectives add settlement_reset dummy
scoreboard objectives add settlement_q_i dummy
scoreboard objectives add settlement_q_s dummy
scoreboard objectives add settlement_q_t dummy
scoreboard objectives add ability_points dummy
scoreboard objectives add spent_mp dummy
scoreboard objectives add earned_mp dummy
scoreboard objectives add actionbar_update dummy
scoreboard objectives add oaklogue_cd dummy
scoreboard objectives add exp_gained dummy
scoreboard objectives add exp_level dummy
scoreboard objectives add levelup_cd dummy
scoreboard objectives add cabbage_cart dummy
scoreboard objectives add player_dead dummy
scoreboard objectives add 20hz dummy
scoreboard objectives add qtitle_delay dummy
scoreboard objectives add collected_tiles dummy
scoreboard players add @e[name=main] collected_tiles 0
scoreboard objectives add placed_tiles dummy
scoreboard players add @e[name=main] placed_tiles 0
scoreboard objectives add tile_place_cd dummy
scoreboard objectives add reset_count dummy
scoreboard players add @e[name=main] reset_count 0
scoreboard objectives add reset_result dummy
scoreboard objectives add reset_result dummy
scoreboard objectives add av_state_level dummy
scoreboard players add @e[name=main] av_state_level 0
scoreboard objectives add av_state_time dummy
scoreboard objectives add av_state_cd dummy
scoreboard objectives add return_point_id dummy
scoreboard objectives add bounds_time dummy
scoreboard objectives add whistle_time dummy
scoreboard objectives add active_region dummy
scoreboard objectives add region_result dummy
scoreboard players add @e[name=main] active_region 0
scoreboard objectives add travel_time dummy
scoreboard objectives add travel_dest dummy
scoreboard objectives add mastery dummy