stopsound @a music.random.track1
stopsound @a music.random.track2
stopsound @a music.random.track3
stopsound @a music.random.track4
stopsound @a music.random.track5
stopsound @a music.random.track6
stopsound @a music.random.track7
stopsound @a music.random.track8
stopsound @a music.random.track9
stopsound @a music.random.track10
stopsound @a music.random.track11
stopsound @a music.random.track12
stopsound @a music.random.track13
stopsound @a music.random.track14
stopsound @a music.random.track15
stopsound @a music.random.track16
stopsound @a music.random.track17
stopsound @a music.random.track18
stopsound @a duel_music_loop
stopsound @a duel_music_loop2
stopsound @a duel_music_loop3
stopsound @a duel_music_loop4
stopsound @a duel_music_loop5
stopsound @a duel_music_loop6
stopsound @a encampment_music_loop
stopsound @a leaves_from_the_vine