scoreboard players operation @s ability_points = @e[name=main] earned_mp
scoreboard players operation @s ability_points -= @s spent_mp
xp -999L @s
execute @s[scores={ability_points=1}] ~ ~ ~ xp 1L @s
execute @s[scores={ability_points=2}] ~ ~ ~ xp 2L @s
execute @s[scores={ability_points=3}] ~ ~ ~ xp 3L @s
execute @s[scores={ability_points=4}] ~ ~ ~ xp 4L @s
execute @s[scores={ability_points=5}] ~ ~ ~ xp 5L @s
execute @s[scores={ability_points=6}] ~ ~ ~ xp 6L @s
execute @s[scores={ability_points=7}] ~ ~ ~ xp 7L @s
execute @s[scores={ability_points=8}] ~ ~ ~ xp 8L @s
execute @s[scores={ability_points=9}] ~ ~ ~ xp 9L @s
execute @s[scores={ability_points=10}] ~ ~ ~ xp 10L @s
execute @s[scores={ability_points=11}] ~ ~ ~ xp 11L @s
execute @s[scores={ability_points=12}] ~ ~ ~ xp 12L @s
execute @s[scores={ability_points=13}] ~ ~ ~ xp 13L @s
execute @s[scores={ability_points=14}] ~ ~ ~ xp 14L @s
execute @s[scores={ability_points=15}] ~ ~ ~ xp 15L @s
execute @s[scores={ability_points=16}] ~ ~ ~ xp 16L @s
execute @s[scores={ability_points=17}] ~ ~ ~ xp 17L @s
execute @s[scores={ability_points=18}] ~ ~ ~ xp 18L @s
execute @s[scores={ability_points=19}] ~ ~ ~ xp 19L @s
execute @s[scores={ability_points=20}] ~ ~ ~ xp 20L @s
execute @s[scores={ability_points=21}] ~ ~ ~ xp 21L @s
execute @s[scores={ability_points=22}] ~ ~ ~ xp 22L @s
execute @s[scores={ability_points=23}] ~ ~ ~ xp 23L @s
execute @s[scores={ability_points=24}] ~ ~ ~ xp 24L @s
execute @s[scores={ability_points=25}] ~ ~ ~ xp 25L @s
execute @s[scores={ability_points=26}] ~ ~ ~ xp 26L @s
execute @s[scores={ability_points=27}] ~ ~ ~ xp 27L @s
execute @s[scores={ability_points=28}] ~ ~ ~ xp 28L @s
execute @s[scores={ability_points=29}] ~ ~ ~ xp 29L @s
execute @s[scores={ability_points=30}] ~ ~ ~ xp 30L @s
execute @s[scores={ability_points=31}] ~ ~ ~ xp 31L @s
execute @s[scores={ability_points=32}] ~ ~ ~ xp 32L @s
execute @s[scores={ability_points=33}] ~ ~ ~ xp 33L @s
execute @s[scores={ability_points=34}] ~ ~ ~ xp 34L @s
execute @s[scores={ability_points=35}] ~ ~ ~ xp 35L @s
execute @s[scores={ability_points=36}] ~ ~ ~ xp 36L @s
execute @s[scores={ability_points=37}] ~ ~ ~ xp 37L @s
execute @s[scores={ability_points=38}] ~ ~ ~ xp 38L @s
execute @s[scores={ability_points=39}] ~ ~ ~ xp 39L @s
execute @s[scores={ability_points=40}] ~ ~ ~ xp 40L @s
execute @s[scores={ability_points=41}] ~ ~ ~ xp 41L @s
execute @s[scores={ability_points=42}] ~ ~ ~ xp 42L @s
execute @s[scores={ability_points=43}] ~ ~ ~ xp 43L @s
execute @s[scores={ability_points=44}] ~ ~ ~ xp 44L @s
execute @s[scores={ability_points=45}] ~ ~ ~ xp 45L @s
execute @s[scores={ability_points=46}] ~ ~ ~ xp 46L @s
execute @s[scores={ability_points=47}] ~ ~ ~ xp 47L @s
execute @s[scores={ability_points=48}] ~ ~ ~ xp 48L @s
execute @s[scores={ability_points=49}] ~ ~ ~ xp 49L @s
execute @s[scores={ability_points=50}] ~ ~ ~ xp 50L @s