damage @s[scores={del_dmg_amnt=1}] 1 none
damage @s[scores={del_dmg_amnt=2}] 2 none
damage @s[scores={del_dmg_amnt=3}] 3 none
damage @s[scores={del_dmg_amnt=4}] 4 none
damage @s[scores={del_dmg_amnt=5}] 5 none
damage @s[scores={del_dmg_amnt=6}] 6 none
damage @s[scores={del_dmg_amnt=7}] 7 none
damage @s[scores={del_dmg_amnt=8}] 8 none
damage @s[scores={del_dmg_amnt=9}] 9 none
damage @s[scores={del_dmg_amnt=10}] 10 none
damage @s[scores={del_dmg_amnt=11}] 11 none
damage @s[scores={del_dmg_amnt=12}] 12 none
damage @s[scores={del_dmg_amnt=13}] 13 none
damage @s[scores={del_dmg_amnt=14}] 14 none
damage @s[scores={del_dmg_amnt=15}] 15 none
damage @s[scores={del_dmg_amnt=16}] 16 none
damage @s[scores={del_dmg_amnt=17}] 17 none
damage @s[scores={del_dmg_amnt=18}] 18 none
damage @s[scores={del_dmg_amnt=19}] 19 none
damage @s[scores={del_dmg_amnt=20}] 20 none