execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true
execute @s ~~~ tp @s ^^-.1 ^ true