execute @s[scores={current_trinket=0},tag=!trinket.aang] ~~~ function trinket/message/aang
execute @s[scores={current_trinket=1},tag=!trinket.amon] ~~~ function trinket/message/amon
execute @s[scores={current_trinket=2},tag=!trinket.asami] ~~~ function trinket/message/asami
execute @s[scores={current_trinket=3},tag=!trinket.azula] ~~~ function trinket/message/azula
execute @s[scores={current_trinket=4},tag=!trinket.bolin] ~~~ function trinket/message/bolin
execute @s[scores={current_trinket=5},tag=!trinket.bumi] ~~~ function trinket/message/bumi
execute @s[scores={current_trinket=6},tag=!trinket.cabbage] ~~~ function trinket/message/cabbage
execute @s[scores={current_trinket=7},tag=!trinket.iroh] ~~~ function trinket/message/iroh
execute @s[scores={current_trinket=8},tag=!trinket.jet] ~~~ function trinket/message/jet
execute @s[scores={current_trinket=9},tag=!trinket.kai] ~~~ function trinket/message/kai
execute @s[scores={current_trinket=10},tag=!trinket.katara] ~~~ function trinket/message/katara
execute @s[scores={current_trinket=11},tag=!trinket.korra] ~~~ function trinket/message/korra
execute @s[scores={current_trinket=12},tag=!trinket.kyoshi] ~~~ function trinket/message/kyoshi
execute @s[scores={current_trinket=13},tag=!trinket.lin] ~~~ function trinket/message/lin
execute @s[scores={current_trinket=14},tag=!trinket.long] ~~~ function trinket/message/long
execute @s[scores={current_trinket=15},tag=!trinket.mako] ~~~ function trinket/message/mako
execute @s[scores={current_trinket=16},tag=!trinket.opal] ~~~ function trinket/message/opal
execute @s[scores={current_trinket=17},tag=!trinket.ozai] ~~~ function trinket/message/ozai
execute @s[scores={current_trinket=18},tag=!trinket.pathik] ~~~ function trinket/message/pathik
execute @s[scores={current_trinket=19},tag=!trinketplayers] ~~~ function trinket/message/players
execute @s[scores={current_trinket=20},tag=!trinket.roku] ~~~ function trinket/message/roku
execute @s[scores={current_trinket=21},tag=!trinket.sokka] ~~~ function trinket/message/sokka
execute @s[scores={current_trinket=22},tag=!trinket.suki] ~~~ function trinket/message/suki
execute @s[scores={current_trinket=23},tag=!trinket.tenzin] ~~~ function trinket/message/tenzin
execute @s[scores={current_trinket=24},tag=!trinket.toph] ~~~ function trinket/message/toph
execute @s[scores={current_trinket=25},tag=!trinket.unalaq] ~~~ function trinket/message/unalaq
execute @s[scores={current_trinket=26},tag=!trinket.varrick] ~~~ function trinket/message/varrick
execute @s[scores={current_trinket=27},tag=!trinket.zaheer] ~~~ function trinket/message/zaheer
execute @s[scores={current_trinket=28},tag=!trinket.zhao] ~~~ function trinket/message/zhao
execute @s[scores={current_trinket=29},tag=!trinket.zuko] ~~~ function trinket/message/zuko