tag @s add oaklogue.selector
execute @e[tag=dialogue.1,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/1
execute @e[tag=dialogue.2,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/2
execute @e[tag=dialogue.3,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/3
execute @e[tag=dialogue.4,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/4
execute @e[tag=dialogue.5,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/5
execute @e[tag=dialogue.6,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/6
execute @e[tag=dialogue.7,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/7
execute @e[tag=dialogue.8,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/8
execute @e[tag=dialogue.9,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/9
execute @e[tag=dialogue.10,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/trivia_bss
execute @e[tag=dialogue.11,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/11
execute @e[tag=dialogue.12,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/12
execute @e[tag=dialogue.13,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/13
execute @e[tag=dialogue.14,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/14
execute @e[tag=dialogue.15,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/15
execute @e[tag=dialogue.16,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/16
execute @e[tag=dialogue.17,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/17
execute @e[tag=dialogue.18,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/18
execute @e[tag=dialogue.19,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/tutorial.duel
execute @e[tag=dialogue.20,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/20
execute @e[tag=dialogue.21,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/21
execute @e[tag=dialogue.22,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/22
execute @e[tag=dialogue.23,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/23
execute @e[tag=dialogue.24,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/24
execute @e[tag=dialogue.25,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/25
execute @e[tag=dialogue.26,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/trivia_emi
execute @e[tag=dialogue.27,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/27
execute @e[tag=dialogue.28,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/28
execute @e[tag=dialogue.29,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/29
execute @e[tag=dialogue.30,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/30
execute @e[tag=dialogue.31,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/31
execute @e[tag=dialogue.32,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/32
execute @e[tag=dialogue.33,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/trivia_swt
execute @e[tag=dialogue.34,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/34
execute @e[tag=dialogue.35,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/35
execute @e[tag=dialogue.36,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/36
execute @e[tag=dialogue.37,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/37
execute @e[tag=dialogue.38,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/38
execute @e[tag=dialogue.39,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/39
execute @e[tag=dialogue.40,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/40
execute @e[tag=dialogue.41,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/trivia_nat
execute @s ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_bss_male/default
tag @s remove oaklogue.selector