damage @s[scores={roar_dmg=1}] 1 lava
damage @s[scores={roar_dmg=2}] 2 lava
damage @s[scores={roar_dmg=3}] 3 lava
damage @s[scores={roar_dmg=4}] 4 lava
damage @s[scores={roar_dmg=5}] 5 lava
damage @s[scores={roar_dmg=6}] 6 lava
damage @s[scores={roar_dmg=7}] 7 lava
damage @s[scores={roar_dmg=8}] 8 lava
damage @s[scores={roar_dmg=9}] 9 lava
damage @s[scores={roar_dmg=10..}] 10 lava