scoreboard players add @s bending_id 0
tag @s[scores={bending_id=0}] add bending_id_self
scoreboard players set @s[tag=bending_id_self] bending_id 1
execute @e[tag=bender,scores={bending_id=1},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=1}] bending_id 1
execute @e[tag=bender,scores={bending_id=2},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=2}] bending_id 1
execute @e[tag=bender,scores={bending_id=3},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=3}] bending_id 1
execute @e[tag=bender,scores={bending_id=4},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=4}] bending_id 1
execute @e[tag=bender,scores={bending_id=5},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=5}] bending_id 1
execute @e[tag=bender,scores={bending_id=6},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=6}] bending_id 1
execute @e[tag=bender,scores={bending_id=7},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=7}] bending_id 1
execute @e[tag=bender,scores={bending_id=8},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=8}] bending_id 1
execute @e[tag=bender,scores={bending_id=9},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=9}] bending_id 1
execute @e[tag=bender,scores={bending_id=10},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=10}] bending_id 1
execute @e[tag=bender,scores={bending_id=11},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=11}] bending_id 1
execute @e[tag=bender,scores={bending_id=12},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=12}] bending_id 1
execute @e[tag=bender,scores={bending_id=13},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=13}] bending_id 1
execute @e[tag=bender,scores={bending_id=14},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=14}] bending_id 1
execute @e[tag=bender,scores={bending_id=15},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=15}] bending_id 1
execute @e[tag=bender,scores={bending_id=16},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=16}] bending_id 1
execute @e[tag=bender,scores={bending_id=17},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=17}] bending_id 1
execute @e[tag=bender,scores={bending_id=18},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=18}] bending_id 1
execute @e[tag=bender,scores={bending_id=19},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=19}] bending_id 1
execute @e[tag=bender,scores={bending_id=20},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=20}] bending_id 1
execute @e[tag=bender,scores={bending_id=21},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=21}] bending_id 1
execute @e[tag=bender,scores={bending_id=22},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=22}] bending_id 1
execute @e[tag=bender,scores={bending_id=23},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=23}] bending_id 1
execute @e[tag=bender,scores={bending_id=24},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=24}] bending_id 1
execute @e[tag=bender,scores={bending_id=25},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=25}] bending_id 1
execute @e[tag=bender,scores={bending_id=26},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=26}] bending_id 1
execute @e[tag=bender,scores={bending_id=27},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=27}] bending_id 1
execute @e[tag=bender,scores={bending_id=28},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=28}] bending_id 1
execute @e[tag=bender,scores={bending_id=29},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=29}] bending_id 1
execute @e[tag=bender,scores={bending_id=30},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=30}] bending_id 1
execute @e[tag=bender,scores={bending_id=31},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=31}] bending_id 1
execute @e[tag=bender,scores={bending_id=32},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=32}] bending_id 1
execute @e[tag=bender,scores={bending_id=33},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=33}] bending_id 1
execute @e[tag=bender,scores={bending_id=34},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=34}] bending_id 1
execute @e[tag=bender,scores={bending_id=35},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=35}] bending_id 1
execute @e[tag=bender,scores={bending_id=36},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=36}] bending_id 1
execute @e[tag=bender,scores={bending_id=37},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=37}] bending_id 1
execute @e[tag=bender,scores={bending_id=38},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=38}] bending_id 1
execute @e[tag=bender,scores={bending_id=39},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=39}] bending_id 1
execute @e[tag=bender,scores={bending_id=40},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=40}] bending_id 1
execute @e[tag=bender,scores={bending_id=41},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=41}] bending_id 1
execute @e[tag=bender,scores={bending_id=42},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=42}] bending_id 1
execute @e[tag=bender,scores={bending_id=43},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=43}] bending_id 1
execute @e[tag=bender,scores={bending_id=44},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=44}] bending_id 1
execute @e[tag=bender,scores={bending_id=45},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=45}] bending_id 1
execute @e[tag=bender,scores={bending_id=46},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=46}] bending_id 1
execute @e[tag=bender,scores={bending_id=47},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=47}] bending_id 1
execute @e[tag=bender,scores={bending_id=48},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=48}] bending_id 1
execute @e[tag=bender,scores={bending_id=49},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=49}] bending_id 1
execute @e[tag=bender,scores={bending_id=50},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=50}] bending_id 1
execute @e[tag=bender,scores={bending_id=51},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=51}] bending_id 1
execute @e[tag=bender,scores={bending_id=52},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=52}] bending_id 1
execute @e[tag=bender,scores={bending_id=53},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=53}] bending_id 1
execute @e[tag=bender,scores={bending_id=54},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=54}] bending_id 1
execute @e[tag=bender,scores={bending_id=55},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=55}] bending_id 1
execute @e[tag=bender,scores={bending_id=56},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=56}] bending_id 1
execute @e[tag=bender,scores={bending_id=57},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=57}] bending_id 1
execute @e[tag=bender,scores={bending_id=58},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=58}] bending_id 1
execute @e[tag=bender,scores={bending_id=59},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=59}] bending_id 1
execute @e[tag=bender,scores={bending_id=60},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=60}] bending_id 1
execute @e[tag=bender,scores={bending_id=61},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=61}] bending_id 1
execute @e[tag=bender,scores={bending_id=62},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=62}] bending_id 1
execute @e[tag=bender,scores={bending_id=63},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=63}] bending_id 1
execute @e[tag=bender,scores={bending_id=64},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=64}] bending_id 1
execute @e[tag=bender,scores={bending_id=65},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=65}] bending_id 1
execute @e[tag=bender,scores={bending_id=66},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=66}] bending_id 1
execute @e[tag=bender,scores={bending_id=67},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=67}] bending_id 1
execute @e[tag=bender,scores={bending_id=68},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=68}] bending_id 1
execute @e[tag=bender,scores={bending_id=69},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=69}] bending_id 1
execute @e[tag=bender,scores={bending_id=70},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=70}] bending_id 1
execute @e[tag=bender,scores={bending_id=71},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=71}] bending_id 1
execute @e[tag=bender,scores={bending_id=72},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=72}] bending_id 1
execute @e[tag=bender,scores={bending_id=73},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=73}] bending_id 1
execute @e[tag=bender,scores={bending_id=74},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=74}] bending_id 1
execute @e[tag=bender,scores={bending_id=75},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=75}] bending_id 1
execute @e[tag=bender,scores={bending_id=76},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=76}] bending_id 1
execute @e[tag=bender,scores={bending_id=77},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=77}] bending_id 1
execute @e[tag=bender,scores={bending_id=78},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=78}] bending_id 1
execute @e[tag=bender,scores={bending_id=79},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=79}] bending_id 1
execute @e[tag=bender,scores={bending_id=80},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=80}] bending_id 1
execute @e[tag=bender,scores={bending_id=81},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=81}] bending_id 1
execute @e[tag=bender,scores={bending_id=82},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=82}] bending_id 1
execute @e[tag=bender,scores={bending_id=83},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=83}] bending_id 1
execute @e[tag=bender,scores={bending_id=84},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=84}] bending_id 1
execute @e[tag=bender,scores={bending_id=85},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=85}] bending_id 1
execute @e[tag=bender,scores={bending_id=86},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=86}] bending_id 1
execute @e[tag=bender,scores={bending_id=87},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=87}] bending_id 1
execute @e[tag=bender,scores={bending_id=88},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=88}] bending_id 1
execute @e[tag=bender,scores={bending_id=89},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=89}] bending_id 1
execute @e[tag=bender,scores={bending_id=90},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=90}] bending_id 1
execute @e[tag=bender,scores={bending_id=91},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=91}] bending_id 1
execute @e[tag=bender,scores={bending_id=92},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=92}] bending_id 1
execute @e[tag=bender,scores={bending_id=93},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=93}] bending_id 1
execute @e[tag=bender,scores={bending_id=94},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=94}] bending_id 1
execute @e[tag=bender,scores={bending_id=95},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=95}] bending_id 1
execute @e[tag=bender,scores={bending_id=96},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=96}] bending_id 1
execute @e[tag=bender,scores={bending_id=97},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=97}] bending_id 1
execute @e[tag=bender,scores={bending_id=98},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=98}] bending_id 1
execute @e[tag=bender,scores={bending_id=99},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=99}] bending_id 1
execute @e[tag=bender,scores={bending_id=100},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=100}] bending_id 1
execute @e[tag=bender,scores={bending_id=101},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=101}] bending_id 1
execute @e[tag=bender,scores={bending_id=102},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=102}] bending_id 1
execute @e[tag=bender,scores={bending_id=103},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=103}] bending_id 1
execute @e[tag=bender,scores={bending_id=104},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=104}] bending_id 1
execute @e[tag=bender,scores={bending_id=105},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=105}] bending_id 1
execute @e[tag=bender,scores={bending_id=106},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=106}] bending_id 1
execute @e[tag=bender,scores={bending_id=107},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=107}] bending_id 1
execute @e[tag=bender,scores={bending_id=108},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=108}] bending_id 1
execute @e[tag=bender,scores={bending_id=109},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=109}] bending_id 1
execute @e[tag=bender,scores={bending_id=110},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=110}] bending_id 1
execute @e[tag=bender,scores={bending_id=111},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=111}] bending_id 1
execute @e[tag=bender,scores={bending_id=112},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=112}] bending_id 1
execute @e[tag=bender,scores={bending_id=113},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=113}] bending_id 1
execute @e[tag=bender,scores={bending_id=114},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=114}] bending_id 1
execute @e[tag=bender,scores={bending_id=115},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=115}] bending_id 1
execute @e[tag=bender,scores={bending_id=116},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=116}] bending_id 1
execute @e[tag=bender,scores={bending_id=117},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=117}] bending_id 1
execute @e[tag=bender,scores={bending_id=118},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=118}] bending_id 1
execute @e[tag=bender,scores={bending_id=119},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=119}] bending_id 1
execute @e[tag=bender,scores={bending_id=120},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=120}] bending_id 1
execute @e[tag=bender,scores={bending_id=121},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=121}] bending_id 1
execute @e[tag=bender,scores={bending_id=122},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=122}] bending_id 1
execute @e[tag=bender,scores={bending_id=123},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=123}] bending_id 1
execute @e[tag=bender,scores={bending_id=124},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=124}] bending_id 1
execute @e[tag=bender,scores={bending_id=125},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=125}] bending_id 1
execute @e[tag=bender,scores={bending_id=126},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=126}] bending_id 1
execute @e[tag=bender,scores={bending_id=127},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=127}] bending_id 1
execute @e[tag=bender,scores={bending_id=128},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=128}] bending_id 1
execute @e[tag=bender,scores={bending_id=129},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=129}] bending_id 1
execute @e[tag=bender,scores={bending_id=130},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=130}] bending_id 1
execute @e[tag=bender,scores={bending_id=131},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=131}] bending_id 1
execute @e[tag=bender,scores={bending_id=132},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=132}] bending_id 1
execute @e[tag=bender,scores={bending_id=133},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=133}] bending_id 1
execute @e[tag=bender,scores={bending_id=134},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=134}] bending_id 1
execute @e[tag=bender,scores={bending_id=135},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=135}] bending_id 1
execute @e[tag=bender,scores={bending_id=136},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=136}] bending_id 1
execute @e[tag=bender,scores={bending_id=137},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=137}] bending_id 1
execute @e[tag=bender,scores={bending_id=138},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=138}] bending_id 1
execute @e[tag=bender,scores={bending_id=139},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=139}] bending_id 1
execute @e[tag=bender,scores={bending_id=140},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=140}] bending_id 1
execute @e[tag=bender,scores={bending_id=141},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=141}] bending_id 1
execute @e[tag=bender,scores={bending_id=142},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=142}] bending_id 1
execute @e[tag=bender,scores={bending_id=143},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=143}] bending_id 1
execute @e[tag=bender,scores={bending_id=144},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=144}] bending_id 1
execute @e[tag=bender,scores={bending_id=145},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=145}] bending_id 1
execute @e[tag=bender,scores={bending_id=146},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=146}] bending_id 1
execute @e[tag=bender,scores={bending_id=147},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=147}] bending_id 1
execute @e[tag=bender,scores={bending_id=148},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=148}] bending_id 1
execute @e[tag=bender,scores={bending_id=149},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=149}] bending_id 1
execute @e[tag=bender,scores={bending_id=150},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=150}] bending_id 1
execute @e[tag=bender,scores={bending_id=151},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=151}] bending_id 1
execute @e[tag=bender,scores={bending_id=152},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=152}] bending_id 1
execute @e[tag=bender,scores={bending_id=153},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=153}] bending_id 1
execute @e[tag=bender,scores={bending_id=154},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=154}] bending_id 1
execute @e[tag=bender,scores={bending_id=155},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=155}] bending_id 1
execute @e[tag=bender,scores={bending_id=156},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=156}] bending_id 1
execute @e[tag=bender,scores={bending_id=157},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=157}] bending_id 1
execute @e[tag=bender,scores={bending_id=158},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=158}] bending_id 1
execute @e[tag=bender,scores={bending_id=159},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=159}] bending_id 1
execute @e[tag=bender,scores={bending_id=160},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=160}] bending_id 1
execute @e[tag=bender,scores={bending_id=161},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=161}] bending_id 1
execute @e[tag=bender,scores={bending_id=162},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=162}] bending_id 1
execute @e[tag=bender,scores={bending_id=163},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=163}] bending_id 1
execute @e[tag=bender,scores={bending_id=164},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=164}] bending_id 1
execute @e[tag=bender,scores={bending_id=165},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=165}] bending_id 1
execute @e[tag=bender,scores={bending_id=166},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=166}] bending_id 1
execute @e[tag=bender,scores={bending_id=167},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=167}] bending_id 1
execute @e[tag=bender,scores={bending_id=168},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=168}] bending_id 1
execute @e[tag=bender,scores={bending_id=169},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=169}] bending_id 1
execute @e[tag=bender,scores={bending_id=170},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=170}] bending_id 1
execute @e[tag=bender,scores={bending_id=171},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=171}] bending_id 1
execute @e[tag=bender,scores={bending_id=172},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=172}] bending_id 1
execute @e[tag=bender,scores={bending_id=173},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=173}] bending_id 1
execute @e[tag=bender,scores={bending_id=174},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=174}] bending_id 1
execute @e[tag=bender,scores={bending_id=175},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=175}] bending_id 1
execute @e[tag=bender,scores={bending_id=176},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=176}] bending_id 1
execute @e[tag=bender,scores={bending_id=177},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=177}] bending_id 1
execute @e[tag=bender,scores={bending_id=178},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=178}] bending_id 1
execute @e[tag=bender,scores={bending_id=179},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=179}] bending_id 1
execute @e[tag=bender,scores={bending_id=180},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=180}] bending_id 1
execute @e[tag=bender,scores={bending_id=181},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=181}] bending_id 1
execute @e[tag=bender,scores={bending_id=182},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=182}] bending_id 1
execute @e[tag=bender,scores={bending_id=183},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=183}] bending_id 1
execute @e[tag=bender,scores={bending_id=184},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=184}] bending_id 1
execute @e[tag=bender,scores={bending_id=185},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=185}] bending_id 1
execute @e[tag=bender,scores={bending_id=186},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=186}] bending_id 1
execute @e[tag=bender,scores={bending_id=187},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=187}] bending_id 1
execute @e[tag=bender,scores={bending_id=188},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=188}] bending_id 1
execute @e[tag=bender,scores={bending_id=189},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=189}] bending_id 1
execute @e[tag=bender,scores={bending_id=190},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=190}] bending_id 1
execute @e[tag=bender,scores={bending_id=191},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=191}] bending_id 1
execute @e[tag=bender,scores={bending_id=192},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=192}] bending_id 1
execute @e[tag=bender,scores={bending_id=193},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=193}] bending_id 1
execute @e[tag=bender,scores={bending_id=194},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=194}] bending_id 1
execute @e[tag=bender,scores={bending_id=195},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=195}] bending_id 1
execute @e[tag=bender,scores={bending_id=196},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=196}] bending_id 1
execute @e[tag=bender,scores={bending_id=197},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=197}] bending_id 1
execute @e[tag=bender,scores={bending_id=198},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=198}] bending_id 1
execute @e[tag=bender,scores={bending_id=199},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=199}] bending_id 1
execute @e[tag=bender,scores={bending_id=200},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=200}] bending_id 1
execute @e[tag=bender,scores={bending_id=201},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=201}] bending_id 1
execute @e[tag=bender,scores={bending_id=202},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=202}] bending_id 1
execute @e[tag=bender,scores={bending_id=203},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=203}] bending_id 1
execute @e[tag=bender,scores={bending_id=204},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=204}] bending_id 1
execute @e[tag=bender,scores={bending_id=205},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=205}] bending_id 1
execute @e[tag=bender,scores={bending_id=206},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=206}] bending_id 1
execute @e[tag=bender,scores={bending_id=207},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=207}] bending_id 1
execute @e[tag=bender,scores={bending_id=208},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=208}] bending_id 1
execute @e[tag=bender,scores={bending_id=209},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=209}] bending_id 1
execute @e[tag=bender,scores={bending_id=210},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=210}] bending_id 1
execute @e[tag=bender,scores={bending_id=211},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=211}] bending_id 1
execute @e[tag=bender,scores={bending_id=212},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=212}] bending_id 1
execute @e[tag=bender,scores={bending_id=213},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=213}] bending_id 1
execute @e[tag=bender,scores={bending_id=214},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=214}] bending_id 1
execute @e[tag=bender,scores={bending_id=215},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=215}] bending_id 1
execute @e[tag=bender,scores={bending_id=216},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=216}] bending_id 1
execute @e[tag=bender,scores={bending_id=217},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=217}] bending_id 1
execute @e[tag=bender,scores={bending_id=218},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=218}] bending_id 1
execute @e[tag=bender,scores={bending_id=219},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=219}] bending_id 1
execute @e[tag=bender,scores={bending_id=220},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=220}] bending_id 1
execute @e[tag=bender,scores={bending_id=221},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=221}] bending_id 1
execute @e[tag=bender,scores={bending_id=222},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=222}] bending_id 1
execute @e[tag=bender,scores={bending_id=223},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=223}] bending_id 1
execute @e[tag=bender,scores={bending_id=224},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=224}] bending_id 1
execute @e[tag=bender,scores={bending_id=225},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=225}] bending_id 1
execute @e[tag=bender,scores={bending_id=226},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=226}] bending_id 1
execute @e[tag=bender,scores={bending_id=227},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=227}] bending_id 1
execute @e[tag=bender,scores={bending_id=228},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=228}] bending_id 1
execute @e[tag=bender,scores={bending_id=229},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=229}] bending_id 1
execute @e[tag=bender,scores={bending_id=230},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=230}] bending_id 1
execute @e[tag=bender,scores={bending_id=231},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=231}] bending_id 1
execute @e[tag=bender,scores={bending_id=232},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=232}] bending_id 1
execute @e[tag=bender,scores={bending_id=233},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=233}] bending_id 1
execute @e[tag=bender,scores={bending_id=234},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=234}] bending_id 1
execute @e[tag=bender,scores={bending_id=235},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=235}] bending_id 1
execute @e[tag=bender,scores={bending_id=236},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=236}] bending_id 1
execute @e[tag=bender,scores={bending_id=237},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=237}] bending_id 1
execute @e[tag=bender,scores={bending_id=238},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=238}] bending_id 1
execute @e[tag=bender,scores={bending_id=239},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=239}] bending_id 1
execute @e[tag=bender,scores={bending_id=240},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=240}] bending_id 1
execute @e[tag=bender,scores={bending_id=241},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=241}] bending_id 1
execute @e[tag=bender,scores={bending_id=242},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=242}] bending_id 1
execute @e[tag=bender,scores={bending_id=243},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=243}] bending_id 1
execute @e[tag=bender,scores={bending_id=244},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=244}] bending_id 1
execute @e[tag=bender,scores={bending_id=245},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=245}] bending_id 1
execute @e[tag=bender,scores={bending_id=246},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=246}] bending_id 1
execute @e[tag=bender,scores={bending_id=247},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=247}] bending_id 1
execute @e[tag=bender,scores={bending_id=248},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=248}] bending_id 1
execute @e[tag=bender,scores={bending_id=249},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=249}] bending_id 1
execute @e[tag=bender,scores={bending_id=250},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=250}] bending_id 1
execute @e[tag=bender,scores={bending_id=251},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=251}] bending_id 1
execute @e[tag=bender,scores={bending_id=252},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=252}] bending_id 1
execute @e[tag=bender,scores={bending_id=253},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=253}] bending_id 1
execute @e[tag=bender,scores={bending_id=254},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=254}] bending_id 1
execute @e[tag=bender,scores={bending_id=255},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=255}] bending_id 1
execute @e[tag=bender,scores={bending_id=256},tag=!bending_id_self] ~ ~ ~ scoreboard players add @e[tag=bending_id_self,scores={bending_id=256}] bending_id 1
tag @s remove bending_id_self
function bending/id/remove_tag
function bending/id/set_tag