tag @s remove rc_e_single_found_stone
tag @s remove rc_e_single_found_dirt
tag @s remove rc_e_single_found_grass
tag @s remove rc_e_single_found_diorite
tag @s remove rc_e_single_found_stonebrick
tag @s remove rc_e_single_found_gravel
tag @s remove rc_e_single_found_cobblestone
tag @s remove rc_e_single_found_andesite
tag @s remove rc_e_single_found_polished_andesite
tag @s remove rc_e_single_found_snow
tag @s remove rc_e_single_found_course_dirt
tag @s remove rc_e_single_found_granite
tag @s remove rc_e_single_found_sand
tag @s remove rc_e_single_found_red_sand
tag @s remove rc_e_single_found_black_concrete
tag @s remove rc_e_single_found_red_concrete
tag @s remove rc_e_single_found_rar_floor
tag @s remove rc_e_single_found_barrier