execute @s ~~~ detect ~~~ stone 0 event entity @s nom:type_0
execute @s ~~~ detect ~~~ stone_block_slab4 2 event entity @s nom:type_0
execute @s ~~~ detect ~~~ double_stone_block_slab4 2 event entity @s nom:type_0
execute @s ~~~ detect ~~~ normal_stone_stairs -1 event entity @s nom:type_0
execute @s ~~~ detect ~~~ dirt 0 event entity @s nom:type_1
execute @s ~~~ detect ~~~ grass -1 event entity @s nom:type_2
execute @s ~~~ detect ~~~ stone 3 event entity @s nom:type_3
execute @s ~~~ detect ~~~ stone_block_slab3 4 event entity @s nom:type_3
execute @s ~~~ detect ~~~ double_stone_block_slab3 4 event entity @s nom:type_3
execute @s ~~~ detect ~~~ diorite_stairs -1 event entity @s nom:type_3
execute @s ~~~ detect ~~~ stonebrick -1 event entity @s nom:type_4
execute @s ~~~ detect ~~~ stone_block_slab 5 event entity @s nom:type_4
execute @s ~~~ detect ~~~ double_stone_block_slab 5 event entity @s nom:type_4
execute @s ~~~ detect ~~~ stone_brick_stairs -1 event entity @s nom:type_4
execute @s ~~~ detect ~~~ red_glazed_terracotta -1 event entity @s nom:type_4
execute @s ~~~ detect ~~~ black_glazed_terracotta -1 event entity @s nom:type_4
execute @s ~~~ detect ~~~ white_glazed_terracotta -1 event entity @s nom:type_4
execute @s ~~~ detect ~~~ wool 3 event entity @s nom:type_4
execute @s ~~~ detect ~~~ gravel -1 event entity @s nom:type_5
execute @s ~~~ detect ~~~ cobblestone -1 event entity @s nom:type_6
execute @s ~~~ detect ~~~ stone_block_slab 3 event entity @s nom:type_6
execute @s ~~~ detect ~~~ double_stone_block_slab 3 event entity @s nom:type_6
execute @s ~~~ detect ~~~ stone_stairs -1 event entity @s nom:type_6
execute @s ~~~ detect ~~~ stone 5 event entity @s nom:type_7
execute @s ~~~ detect ~~~ andesite_stairs -1 event entity @s nom:type_7
execute @s ~~~ detect ~~~ stone_block_slab3 3 event entity @s nom:type_7
execute @s ~~~ detect ~~~ double_stone_block_slab3 3 event entity @s nom:type_7
execute @s ~~~ detect ~~~ stone 6 event entity @s nom:type_8
execute @s ~~~ detect ~~~ stone_block_slab3 2 event entity @s nom:type_8
execute @s ~~~ detect ~~~ polished_andesite_stairs -1 event entity @s nom:type_8
execute @s ~~~ detect ~~~ double_stone_block_slab3 2 event entity @s nom:type_8
execute @s ~~~ detect ~~~ snow_layer -1 event entity @s nom:type_9
execute @s ~~~ detect ~~~ snow -1 event entity @s nom:type_9
execute @s ~~~ detect ~~~ podzol -1 event entity @s nom:type_9
execute @s ~~~ detect ~~~ gray_glazed_terracotta -1 event entity @s nom:type_9
execute @s ~~~ detect ~~~ silver_glazed_terracotta -1 event entity @s nom:type_9
execute @s ~~~ detect ~~~ dirt 1 event entity @s nom:type_10
execute @s ~~~ detect ~~~ stone 1 event entity @s nom:type_11
execute @s ~~~ detect ~~~ granite_stairs -1 event entity @s nom:type_11
execute @s ~~~ detect ~~~ stone_block_slab3 6 event entity @s nom:type_11
execute @s ~~~ detect ~~~ double_stone_block_slab3 6 event entity @s nom:type_11
execute @s ~~~ detect ~~~ sand 0 event entity @s nom:type_12
execute @s ~~~ detect ~~~ sand 1 event entity @s nom:type_13
execute @s ~~~ detect ~~~ concrete 15 event entity @s nom:type_14
execute @s ~~~ detect ~~~ concrete 14 event entity @s nom:type_15
execute @s ~~~ detect ~~~ polished_blackstone -1 event entity @s nom:type_15
execute @s ~~~ detect ~~~ green_glazed_terracotta -1 event entity @s nom:type_15
execute @s ~~~ detect ~~~ stained_hardened_clay 15 event entity @s nom:type_16
execute @s ~~~ detect ~~~ orange_glazed_terracotta -1 event entity @s nom:type_16
execute @s ~~~ detect ~~~ brown_glazed_terracotta -1 event entity @s nom:type_16
execute @s ~~~ detect ~~~ lime_glazed_terracotta -1 event entity @s nom:type_16
execute @s ~~~ detect ~~~ yellow_glazed_terracotta -1 event entity @s nom:type_16