tag @s add oaklogue.selector
execute @e[tag=dialogue.1,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/1
execute @e[tag=dialogue.2,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/2
execute @e[tag=dialogue.3,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/3
execute @e[tag=dialogue.4,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/4
execute @e[tag=dialogue.5,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/5
execute @e[tag=dialogue.6,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/6
execute @e[tag=dialogue.7,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/7
execute @e[tag=dialogue.8,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/8
execute @e[tag=dialogue.9,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/9
execute @e[tag=dialogue.10,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/trivia_bss
execute @e[tag=dialogue.11,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/11
execute @e[tag=dialogue.12,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/12
execute @e[tag=dialogue.13,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/13
execute @e[tag=dialogue.14,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/14
execute @e[tag=dialogue.15,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/15
execute @e[tag=dialogue.16,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/16
execute @e[tag=dialogue.17,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/17
execute @e[tag=dialogue.18,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/18
execute @e[tag=dialogue.19,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/tutorial.duel
execute @e[tag=dialogue.20,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/20
execute @e[tag=dialogue.21,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/21
execute @e[tag=dialogue.22,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/22
execute @e[tag=dialogue.23,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/23
execute @e[tag=dialogue.24,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/24
execute @e[tag=dialogue.25,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/25
execute @e[tag=dialogue.26,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/trivia_emi
execute @e[tag=dialogue.27,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/27
execute @e[tag=dialogue.28,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/28
execute @e[tag=dialogue.29,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/29
execute @e[tag=dialogue.30,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/30
execute @e[tag=dialogue.31,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/31
execute @e[tag=dialogue.32,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/32
execute @e[tag=dialogue.33,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/trivia_swt
execute @e[tag=dialogue.34,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/34
execute @e[tag=dialogue.35,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/35
execute @e[tag=dialogue.36,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/36
execute @e[tag=dialogue.37,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/37
execute @e[tag=dialogue.38,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/38
execute @e[tag=dialogue.39,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/39
execute @e[tag=dialogue.40,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/40
execute @e[tag=dialogue.41,tag=oaklogue.speaker.start,c=1] ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/trivia_nat
execute @s ~ ~ ~ execute @e[tag=oaklogue.selector] ~ ~ ~ function oaklogue/citizen_swt_female/default
tag @s remove oaklogue.selector